gsonline/wang9172/apps/courses/urls.py
# _*_ encoding:utf-8 _*_

__author__ = 'wang'


from django.conf.urls import url
from .views import CourseList, CourseDetail, CourseInfo, CourseComments, \
    AddComments

urlpatterns = [
    url(r'^list/$', CourseList.as_view(), name="course_list"),
    url(r'^course/(?P<course_id>\d+)$', CourseDetail.as_view(), name="detail"),
    url(r'^info/(?P<course_id>\d+)$', CourseInfo.as_view(), name="info"),
    url(r'^comments/(?P<course_id>\d+)$', CourseComments.as_view(),
        name="comments"),
    url(r'^add_comments/$', AddComments.as_view(), name="add_comments")
]

gsonline/wang9172/apps/organization/urls.py
# _*_ encoding:utf:8 _*_

__author__ = 'wang'

from django.conf.urls import url
from organization.views import AskUser, OrgList, OrgHome, CourseHome, \
    TeacherHome, DesHome, \
    FavoriteHome
from organization.teacher import TeacherDetail, TeacherList

urlpatterns = [
    url(r'^user_ask/$', AskUser.as_view(), name="user_ask"),
    url(r'^list/$', OrgList.as_view(), name='list'),
    url(r'^home/(?P<org_id>\d+)$', OrgHome.as_view(), name='org_home'),
    url(r'^course/(?P<org_id>\d+)$', CourseHome.as_view(), name='org_course'),
    url(r'^org_teacher/(?P<org_id>\d+)$', TeacherHome.as_view(),
        name='org_teacher'),
    url(r'^des/(?P<org_id>\d+)$', DesHome.as_view(), name='des'),
    url(r'^add_fav/$', FavoriteHome.as_view(), name='add_fav'),
    url(r'^teacher/list/$', TeacherList.as_view(), name='teacher_list'),
    url(r'^teacher/detail/(?P<teacher_id>\d+)$', TeacherDetail.as_view(),
        name='teacher_detail'),
]

gsonline/wang9172/apps/users/urls.py
# _*_ encoding:utf-8 _*_

__author__ = 'wang'

from django.conf.urls import url
from .views import UserCenter, UploadUserImage, ChangePwdView, \
    UserCenterSendEmail, CheckCode, UpdateUserInfo, UserCourseDetail, \
    UserFavOrg, UserFavCourse, UserFavTeacher, MyMessage

urlpatterns = [
    url(r'^center/(?P<user_id>\d+)$', UserCenter.as_view(),
        name='user_center'),
    # 用户头像上传
    url(r'^image/upload/$', UploadUserImage.as_view(), name='image_upload'),
    # 用户个人中心修改密码
    url(r'^update/pwd/$', ChangePwdView.as_view(), name='update_pwd'),
    # 用户个人中心修改密码
    url(r'^send/email/$', UserCenterSendEmail.as_view(), name='send_email'),
    # 用户个人往邮箱发送验证码
    url(r'^check/code/$', CheckCode.as_view(), name='check_code'),
    # 个人中心修改用户信息
    url(r'^change/info/$', UpdateUserInfo.as_view(), name='change_info'),
    # 个人中心修改用户信息
    url(r'^course/$', UserCourseDetail.as_view(), name='course'),
    # 用户收藏机构
    url(r'^fav/org/$', UserFavOrg.as_view(), name='fav_org'),
    # 用户收藏的课程
    url(r'^fav/course/$', UserFavCourse.as_view(), name='fav_course'),
    # 用户收藏的老师
    url(r'^fav/teacher/$', UserFavTeacher.as_view(), name='fav_teacher'),
    # 个人中心-我的信息
    url(r'^my/message/$', MyMessage.as_view(), name='my_message'),
]

gsonline/wang9172/wang9172/urls.py
# _*_ encoding:utf-8 _*_
"""wang9172 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
# from django.contrib import admin

from django.views.static import serve
from users.views import LoginView, RegisterView, ActiveView, ForgetPassword, \
    ResetPassword, ModifyPwdView, LogOutView, IndexView

from wang9172.settings import MEDIA_ROOT

import xadmin

urlpatterns = [
    # xadmin url
    url(r'^xadmin/', xadmin.site.urls),
    # 首页
    url(r'^$', IndexView.as_view(), name='index'),
    # 登录页面
    url(r'^login/$', LoginView.as_view(), name='login'),
    # 退出登录页面
    url(r'^LoginOut/$', LogOutView.as_view(), name='LoginOut'),
    # 注册页面
    url(r'^register/$', RegisterView.as_view(), name='register'),
    # 忘记密码
    url(r'^forget_pwd/$', ForgetPassword.as_view(), name='forget_pwd'),
    # 验证码
    url(r'^captcha/', include('captcha.urls')),
    # 激活连接
    url(r'^active/(?P<active_code>.*)/$', ActiveView.as_view(), name='active'),
    # 重置连接
    url(r'^reset/(?P<active_code>.*)/$', ResetPassword.as_view(),
        name='reset'),
    url(r'^modify_pwd/$', ModifyPwdView.as_view(), name='modify_pwd'),

    # 配置上传文件访问处理
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),

    # 批量配置课程机构
    url(r'^org/', include('organization.urls', namespace="org")),

    # 配置讲师
    url(r'^teacher/', include('organization.urls', namespace="teacher")),

    # 配置讲师
    url(r'^course/', include('courses.urls', namespace="course")),

    # 用户个人中心
    url(r'^user/', include('users.urls', namespace="user")),

    # 配置上传文件访问处理
    # url(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),

    # 富文本编辑器
    url(r'^ueditor/', include('DjangoUeditor.urls')),
]

# 全局404
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.service_error'
handler403 = 'users.views.no_permission'

gsonline/wang9172/apps/users/models.py
# _*_ encoding:utf8 _*_
from __future__ import unicode_literals
from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.


class UserProfile(AbstractUser):
    nick_name = models.CharField(max_length=50, verbose_name="昵称")
    birthday = models.DateField(max_length=32, null=True, verbose_name="生日")
    gender = models.CharField(max_length=6,
                              choices=(("male", u"男"), ("female", "女")),
                              default="female", verbose_name=u"性别")
    phone = models.CharField(max_length=11, null=True, verbose_name="手机号")
    image = models.ImageField(upload_to="image/%Y/%m",
                              default=u"image/default.png", max_length=100)
    address = models.CharField(max_length=64, verbose_name=u'地址')

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.username

    def get_message_num(self):
        from operation.models import UserMessage
        messages = UserMessage.objects.filter(user=self.id, has_read=0).count()
        return messages


class EmailVerifyRecord(models.Model):
    code = models.CharField(max_length=20, verbose_name=u"验证码")
    email = models.EmailField(verbose_name=u"邮箱")
    send_type = models.CharField(max_length=126, choices=(
        ("register", "注册"), ("forget", "找回密码"), ('change_email', "修改邮箱")),
                                 verbose_name=u"验证码类型")
    send_time = models.DateField(default=datetime.now, verbose_name=u"发送时间")

    class Meta:
        verbose_name = u"邮箱验证码"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.code


class Banner(models.Model):
    title = models.CharField(max_length=124, verbose_name="标题")
    image = models.ImageField(upload_to="banner/%Y/%m", verbose_name="轮播图")
    url = models.URLField(max_length=200, verbose_name="超链接地址")
    index = models.IntegerField(default=1000, verbose_name="顺序")
    add_time = models.DateField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "轮播图"
        verbose_name_plural = verbose_name

gsonline/wang9172/templates/org-detail-desc.html
{% extends 'org_base.html' %}
{% block title %}机构介绍{% endblock %}
{% block right_form %}
    <div class="right companycenter layout">
        <div class="head">
            <h1>机构介绍</h1>
            <a class="green fr more" href="{% url 'org:des' course_org.id %}">查看更多 > </a>
        </div>
       <div class="cont">&nbsp; &nbsp;{{ course_org.desc }}<a href="{{ MEDIA_URL }}{{course_org.image }}"></a></div>
    </div>
{% endblock %}

gsonline/wang9172/templates/org-detail-teachers.html
{% extends 'org_base.html' %}
{% block title %}机构教师{% endblock %}
{% block right_form %}
    <div class="right companycenter layout" >
    {% for teacher in all_teacher %}
        <div class="head">
            <h1>机构讲师</h1>
        </div>
        <div class="messagelist">
            <div class=" butler_list butler-fav-box">

                <dl class="des users">
                    <dt>
                        <a href="">
                        <img width="100" height="100" class="scrollLoading" data-url="{% url 'org:teacher_detail' teacher.id %}" src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                        </a>
                    </dt>
                    <dd>
                        <h1>
                            <a href="">
                            {{ teacher.name }}<span class="key">已认证</span>
                            </a>
                        </h1>
                        <ul class="cont clearfix">
                            <li class="time">工作年限：<span>{{ teacher.work_year }}</span></li>
                            <li class="c7">课程数：<span>{{ teacher.click_nums }}</span></li>
                        </ul>
                    </dd>
                </dl>


            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

gsonline/wang9172/templates/org_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}机构首页{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static "css/reset.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/animate.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "js/plugins/queryCity/css/cityLayout.css" %}">
    {% block custom_js %}
    <script src="{% static "js/jquery.min.js" %}" type="text/javascript"></script>
    <script src="{% static "js/jquery-migrate-1.2.1.min.js" %}" type="text/javascript"></script>
    {% endblock %}
</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">
          {% if request.user.is_authenticated %}
                <div class="top">
                    <div class="wp">
                        <div class="fl">
                            <p>服务电话：<b>33333333</b></p></div>
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ request.user.username }}<img class="down fr"
                                              src="{% static 'images/top_down.png' %}"/>
                                </dd>
                                <dt><img width="20" height="20"
                                         src="{{ MEDIA_URL}}{{ request.user.image }}"/>
                                </dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80"
                                             src="{{ MEDIA_URL}}{{ request.user.image }}"/>
                                    </dt>
                                    <dd>
                                        <h2>admin</h2>
                                        <p>admin</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl"
                                       href="{% url 'user:user_center' request.user.id %}">进入个人中心</a>
                                    <a class="fr" href="/logout/">退出</a>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            {% else %}
                <div class="top">
                    <div class="wp">
                        <a style="color:white" class="fr registerbtn"
                           href="{% url 'register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn"
                           href="{% url 'login' %}">登录</a>
                    </div>

                </div>
            {% endif %}
{% block company_header %}
    <div class="middle companyheader">
        <div class="wp">
            <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
            <div class="head fl">
                <h1>
                    {{ course_org.name }}
                    <img src="{% static 'images/authentication.png' %}"/>
                    <img src="{% static 'images/authentication.png' %}"/>
                </h1>
                <p class="fl">
                    <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                    <span class="precision company-credit" data-star-scope="5.0"></span>
                    <span class="key">5.0</span>
                </p>
            </div>
            <div class="btn fr collectionbtn  notlogin
                 "data-favid="22" data-fav-type="1">{% if has_fav %}收藏{% else %}未收藏{% endif %}
            </div>
        {% csrf_token %}
        </div>
    </div>
{% endblock %}
			</div>
    </header>
</section>
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
			<li><a href="{% url 'org:list' %}">课程机构</a>></li>
			<li>{% block page_path %}机构首页{% endblock %}</li>
		</ul>
	</div>
</section>

<div class="wp list personal_list comp">
    <div class="left">
        <ul>
            <li class="{% ifequal current "home" %}active2{% endifequal %}"><a href="{% url 'org:org_home' course_org.id %}">机构首页</a></li>
            <li class="{% ifequal current "course" %}active2{% endifequal %}"><a href="{% url 'org:org_course' course_org.id %}">机构课程</a></li>
            <li class="{% ifequal current "des" %}active2{% endifequal %}"><a href="{% url 'org:des' course_org.id %}">机构介绍</a></li>
            <li class="{% ifequal current "teacher" %}active2{% endifequal %}"><a href={% url 'org:org_teacher' course_org.id %}>机构讲师</a></li>
        </ul>
    </div>
    {% block right_form %}
    <div class="right companycenter layout grouping" >
        <div class="head">
            <h1>全部课程</h1>
            <a class="green fr more" href="org-detail-course.html">查看更多  >  </a>
        </div>
        <div class="brief group_list">

            <div class="module1_5 box">
                <a href="course-detail.html"><img width="214" src="../media/courses/2016/11/mysql.jpg"/></a>
                <div class="des">
                    <a href="course-detail.html"><h2>django入门</h2></a>
                    <span class="fl">课时：<i class="key">0</i></span>
                    <span class="fr">参加人数：3</span>
                </div>
                <div class="bottom">
                    <span class="fl">工商网</span>
                    <span class="star fr  notlogin
                            " data-favid="13"  data-fav-type="4">
                            0
                        </span>
                </div>
            </div>

            <div class="module1_5 box">
                <a href="course-detail.html"><img width="214" src="../media/courses/2016/11/540e57300001d6d906000338-240-135_mvvGYHL.jpg"/></a>
                <div class="des">
                    <a href="course-detail.html"><h2>django实战项目</h2></a>
                    <span class="fl">课时：<i class="key">0</i></span>
                    <span class="fr">参加人数：0</span>
                </div>
                <div class="bottom">
                    <span class="fl">工商网</span>
                    <span class="star fr  notlogin
                            " data-favid="13"  data-fav-type="4">
                            0
                        </span>
                </div>
            </div>

            <div class="module1_5 box">
                <a href="course-detail.html"><img width="214" src="../media/courses/2016/12/python错误和异常.jpg"/></a>
                <div class="des">
                    <a href="course-detail.html"><h2>python错误和异常</h2></a>
                    <span class="fl">课时：<i class="key">0</i></span>
                    <span class="fr">参加人数：0</span>
                </div>
                <div class="bottom">
                    <span class="fl">工商网</span>
                    <span class="star fr  notlogin
                            " data-favid="13"  data-fav-type="4">
                            0
                        </span>
                </div>
            </div>


        </div>
    </div>
    <div class="right companycenter layout" >
        <div class="head">
            <h1>机构教师</h1>
            <a class="green fr more" href="org-detail-teachers.html">查看更多  >  </a>
        </div>

        <div class="diarys">
            <div class="module5 share company-diary-box" style="padding:10px 0;">
                <div class="left">
                    <img class="pic" src="../media/teacher/2016/11/aobama_CXWwMef.png"/>
                    <p>昵称：{{ request.user.username }}</p>
                </div>
                <div class="right">
                    <div class="top">
                        <div class="fl">
                            <a href=""><h1>java开发教程</h1></a>
                            <span>发表于：2015-10-12</span>
                        </div>
                    </div>
                    <div class="middle" style="border-bottom:0;">课程介绍</div>
                </div>
            </div>
        </div>



    </div>
    <div class="right companycenter layout" >
        <div class="head">
            <h1>机构介绍</h1>
            <a class="green fr more" href="org-detail-desc.html">查看更多  >  </a>
        </div>
        <div class="cont">&nbsp; &nbsp; <p>&nbsp; &nbsp;</p><h1 class="ue_t" label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;"><span style="color:#c0504d;">[键入文档标题]</span></h1><p style="text-align:center;"><strong class="ue_t">[键入文档副标题]</strong></p><h3><span class="ue_t" style="font-family:幼圆">[标题 1]</span></h3><p class="ue_t" style="text-indent:2em;">对于“插入”选项卡上的库，在设计时都充分考虑了其中的项与文档整体外观的协调性。 您可以使用这些库来插入表格、页眉、页脚、列表、封面以及其他文档构建基块。 您创建的图片、图表或关系图也将与当前的文档外观协调一致。</p><p class="ue_t" style="text-indent:2em;"><img src="../media/courses/ueditor/57aa86a0000145c512000460_20161210234050_865.jpg" title="" alt="57aa86a0000145c512000460.jpg"/> </p><h3><span class="ue_t" style="font-family:幼圆">[标题 2]</span></h3><p><img src="http://api.map.baidu.com/staticimage?center=116.410899,39.863624&zoom=11&width=530&height=340&markers=116.404,39.915" width="530" height="340"/> </p><p class="ue_t" style="text-indent:2em;">在“开始”选项卡上，通过从快速样式库中为所选文本选择一种外观，您可以方便地更改文档中所选文本的格式。 您还可以使用“开始”选项卡上的其他控件来直接设置文本格式。大多数控件都允许您选择是使用当前主题外观，还是使用某种直接指定的格式。</p><h3><span class="ue_t" style="font-family:幼圆">[标题 3]</span></h3><p>2016-12-10</p><p class="ue_t">对于“插入”选项卡上的库，在设计时都充分考虑了其中的项与文档整体外观的协调性。 您可以使用这些库来插入表格、页眉、页脚、列表、封面以及其他文档构建基块。 您创建的图片、图表或关系图也将与当前的文档外观协调一致。</p><p class="ue_t"><br/> </p><p><br/></p><p><br/></p><a href="/company/desc/22/"><span class="green">[查看更多]</span></a></div>
    </div>
    {% endblock %}

    <!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->
</div>
<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script type="text/javascript">
    //收藏分享
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"/org/add_fav/",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="{% url 'login' %}";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('.collectionbtn').on('click', function(){
    add_fav($(this), 1, 2);
});

$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '/static/images/',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $('.jsFavBtn').on('click', function(){
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , '收藏');

        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );

        }else if(type == '11'){
            favPraise($(this), 'pra', 1);

        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );

        }
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>

</body>
</html>

gsonline/wang9172/templates/usercenter-fav-course.html
{% extends 'user_center_base.html' %}
{% load staticfiles %}
{% block title %}个人中心-我的收藏{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'user:user_center' user.id %}">个人中心</a>>
                </li>
                <li>个人信息</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block right %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                     <ul class="tab_header messagehead">
                        <li class={% if current == 'fav_org' %}"active"{% endif %}><a href="{% url 'user:fav_org' %}">课程机构</a> </li>
                        <li class={% if current == 'fav_teacher' %}"active"{% endif %}><a href="{% url 'user:fav_teacher' %}">授课教师 </a></li>
                        <li class={% if current == 'fav_course' %}"active"{% endif %}><a href="{% url 'user:fav_course' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in course_list %}
                        <div class="module1_5 box">
                            <a href="{% url 'course:detail' course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_time }}</i></span>
                                <span class="fr">学习人数：{{ course.student_num }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="12"></span>
                            </div>
                        </div>

                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

gsonline/wang9172/templates/usercenter-fav-teacher.html
{% extends 'user_center_base.html' %}
{% load staticfiles %}
{% block title %}个人中心-我的收藏{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'user:user_center' user.id %}">个人中心</a>>
                </li>
                <li>个人信息</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block right %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class={% if current == 'fav_org' %}"active"{% endif %}><a href="{% url 'user:fav_org' %}">课程机构</a> </li>
                        <li class={% if current == 'fav_teacher' %}"active"{% endif %}><a href="{% url 'user:fav_teacher' %}">授课教师 </a></li>
                        <li class={% if current == 'fav_course' %}"active"{% endif %}><a href="{% url 'user:fav_course' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for teacher in teacher_list %}
                    <div class=" butler_list butler-fav-box">
                        <dl class="des users">
                            <dt>
                                <a href="{% url 'teacher:teacher_detail' teacher.id %}">
                                    <img width="100" height="100" src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1>
                                    <a href="{{ MEDIA_URL }}{{ teacher.image }}">
                                        {{ teacher.name }}<span class="key">认证教师</span>
                                    </a>
                                </h1>
                                <ul class="cont clearfix">
                                    <li class="time">工作年限：<span>{{ teacher.work_year }}</span></li>
                                    <li class="c7">课程数：<span>{{ teacher.get_course.count }}</span></li>
                                </ul>
                                <ul class="cont clearfix">
                                    <li class="time">工作公司：<span>{{ teacher.work_company }}</span></li>
                                    <li class="c7">公司职位：<span>{{ teacher.work_positon }}</span></li>
                                </ul>
                            </dd>
                            <div class="delete jsDeleteFav_teacher" data-favid="1"></div>
                        </dl>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}